### ISSUE TITLE
problem configuring and running the project with docker or locally

### ISSUE THREAD

**Issue by fawazal** [MaxxtonGroup/microdocs#70]
hello, I was trying to run the project as it is, but I faced some problems that I could not pass. specially when using the npm link inside the Microdocs-core and then the install inside the Microdocs-server 
I was always stuck at this point

<img width="1427" alt="Screen Shot 2019-04-02 at 6 15 29 PM" src="https://user-images.githubusercontent.com/29060253/55418615-4fcdd400-5573-11e9-8210-07dd6e5cec47.png">

and some files like Microdocs-core-ts does not exist so I replaced it with Microdocs-core and even though when I am trying to do this locally with npm install inside the Microdocs-server ,after the linking; it was still trying to connect to the internet. 

I would be thankful for any response for this problem
kind regards
Fawaz

**Comment by robsonke** [comment]
You have a reference to our NPM server somewhere? That's not publicly available but shouldn't be needed either.

**Comment by FrederikSchlemmer** [comment]
@robsonke thanks for the reply!

I'm also trying to run a local edited version of the server. However, I also have the bug mentioned above.
The server, as well as the UI are trying to load Microdocs-Core and Angular-Rest from your NexusDev. For this I have extended this repository with the repository of [microdocs-core](https://github.com/MaxxtonGroup/microdocs-core) and [angular rest](https://github.com/MaxxtonGroup/angular-rest-client).

First, I built both added repositories with "npm install". Then I changed to the folder microdocs-server and linked the necessary repository 'microdocs-core' with "npm link ../microdocs-core". After that I tried to build the server with "docker-compose up" or "npm install", but I get the above mentioned error, since 'microdocs-core' is still searched in your NexusDev.

How can this be avoided so that the locally linked repositories are used?
Maybe @steven166 can help us out in this situation?

We would like to contribute our changes to this project in the future. We have already implemented YAML support and read source code parts in the crawler.

Many thanks for the help in advance.

**Comment by steven166** [comment]
Hi @FrederikSchlemmer,

The .npmrc file contains the reference to our nexus server. You can remove those in order to resolve you're issue.

Btw. great to hear that you're contributing to this project! :)

**Comment by FrederikSchlemmer** [comment]
@steven166 thanks for the reply!

We got everything working and added some functionality. However, we now have the problem that publishing to the MicroDocs server no longer works with the locally built FatJar of the Gradle plugin (Gradle command: publishMicroDocs).


The error is, but no solutions work:

`Unable to load class 'org.apache.http.nio.reactor.IOReactorException'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)</li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)</li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.`

Has this error already occurred and what is the solution?

**Comment by steven166** [comment]
@FrederikSchlemmer,

I've not seen this error before.
